import type { LanguageCode } from "./locale";

type LocalizedCopy = Record<LanguageCode, string>;

const copyTranslations: Record<string, LocalizedCopy> = {
  "Der Kleinste — kompakt, leicht und schnell einsatzbereit.": {
    de: "Der Kleinste — kompakt, leicht und schnell einsatzbereit.",
    en: "The smallest model — compact, light and ready to go.",
    fr: "Le plus petit modèle — compact, léger et vite opérationnel.",
    nl: "Het kleinste model — compact, licht en snel inzetbaar.",
  },
  "Der X-ray ist unser kompaktestes Modell — leicht genug für den spontanen Einsatz, durchdacht genug für den täglichen Verkauf. Ideal für Märkte, Events und alle, die unkompliziert starten wollen.": {
    de: "Der X-ray ist unser kompaktestes Modell — leicht genug für den spontanen Einsatz, durchdacht genug für den täglichen Verkauf. Ideal für Märkte, Events und alle, die unkompliziert starten wollen.",
    en: "The X-ray is our most compact model: light enough for spontaneous use and thought through for daily sales. Ideal for markets, events and anyone who wants an easy start.",
    fr: "Le X-ray est notre modèle le plus compact : assez léger pour les interventions spontanées et pensé pour la vente quotidienne. Idéal pour les marchés, les événements et les débuts simples.",
    nl: "De X-ray is ons compactste model: licht genoeg voor spontaan gebruik en doordacht voor dagelijkse verkoop. Ideaal voor markten, events en iedereen die eenvoudig wil starten.",
  },
  "Geringes Gewicht — einfach zu ziehen und zu rangieren": {
    de: "Geringes Gewicht — einfach zu ziehen und zu rangieren",
    en: "Low weight — easy to tow and maneuver",
    fr: "Poids réduit — facile à tracter et à manoeuvrer",
    nl: "Laag gewicht — makkelijk te trekken en te manoeuvreren",
  },
  "Kompakte Stellfläche für enge Standorte": {
    de: "Kompakte Stellfläche für enge Standorte",
    en: "Compact footprint for tight locations",
    fr: "Encombrement compact pour les emplacements étroits",
    nl: "Compacte standplaats voor krappe locaties",
  },
  "Schneller Auf- und Abbau": {
    de: "Schneller Auf- und Abbau",
    en: "Quick setup and takedown",
    fr: "Montage et démontage rapides",
    nl: "Snel op- en afbouwen",
  },
  "Solide Grundausstattung, im Konfigurator erweiterbar": {
    de: "Solide Grundausstattung, im Konfigurator erweiterbar",
    en: "Solid base equipment, expandable in the configurator",
    fr: "Équipement de base solide, extensible dans le configurateur",
    nl: "Solide basisuitrusting, uitbreidbaar in de configurator",
  },
  "Der Einstieg — solide Fläche für den ersten Auftritt.": {
    de: "Der Einstieg — solide Fläche für den ersten Auftritt.",
    en: "The entry point — solid space for your first appearance.",
    fr: "Le point d'entrée — une surface solide pour vos débuts.",
    nl: "De instap — solide ruimte voor je eerste optreden.",
  },
  "Der Basis bietet spürbar mehr Fläche für Theke, Technik und Warenpräsentation — der solide Einstieg für alle, die dauerhaft und professionell verkaufen wollen.": {
    de: "Der Basis bietet spürbar mehr Fläche für Theke, Technik und Warenpräsentation — der solide Einstieg für alle, die dauerhaft und professionell verkaufen wollen.",
    en: "The Basis offers noticeably more space for counter, equipment and product presentation: a solid entry model for anyone who wants to sell professionally over the long term.",
    fr: "Le Basis offre nettement plus d'espace pour le comptoir, la technique et la présentation des produits : une entrée solide pour vendre durablement et professionnellement.",
    nl: "De Basis biedt merkbaar meer ruimte voor toonbank, techniek en productpresentatie: een solide instap voor wie duurzaam en professioneel wil verkopen.",
  },
  "Großzügige Grundfläche für Theke und Ausrüstung": {
    de: "Großzügige Grundfläche für Theke und Ausrüstung",
    en: "Generous footprint for counter and equipment",
    fr: "Surface généreuse pour comptoir et équipement",
    nl: "Ruime basis voor toonbank en uitrusting",
  },
  "Vorbereitet für individuelle Konzepte im Konfigurator": {
    de: "Vorbereitet für individuelle Konzepte im Konfigurator",
    en: "Prepared for individual concepts in the configurator",
    fr: "Préparé pour des concepts individuels dans le configurateur",
    nl: "Voorbereid op individuele concepten in de configurator",
  },
  "Robuste Bauweise für den täglichen Einsatz": {
    de: "Robuste Bauweise für den täglichen Einsatz",
    en: "Robust construction for daily use",
    fr: "Construction robuste pour une utilisation quotidienne",
    nl: "Robuuste bouw voor dagelijks gebruik",
  },
  "Gutes Preis-Leistungs-Verhältnis für den Einstieg": {
    de: "Gutes Preis-Leistungs-Verhältnis für den Einstieg",
    en: "Strong value for an entry model",
    fr: "Bon rapport qualité-prix pour démarrer",
    nl: "Sterke prijs-kwaliteitverhouding voor de instap",
  },
  "Der Bestseller — mehr Platz für Theke und Technik.": {
    de: "Der Bestseller — mehr Platz für Theke und Technik.",
    en: "The bestseller — more room for counter and equipment.",
    fr: "Le best-seller — plus d'espace pour comptoir et technique.",
    nl: "De bestseller — meer ruimte voor toonbank en techniek.",
  },
  "Der Standard ist unser meistgebautes Modell — die ausgewogene Mitte aus Fläche, Ausstattungsmöglichkeiten und Preis. Genug Raum für aufwendigere Konzepte, ohne unnötig groß zu sein.": {
    de: "Der Standard ist unser meistgebautes Modell — die ausgewogene Mitte aus Fläche, Ausstattungsmöglichkeiten und Preis. Genug Raum für aufwendigere Konzepte, ohne unnötig groß zu sein.",
    en: "The Standard is our most-built model: the balanced middle ground of space, equipment options and price. Enough room for more elaborate concepts without becoming unnecessarily large.",
    fr: "Le Standard est notre modèle le plus construit : l'équilibre entre surface, possibilités d'équipement et prix. Assez d'espace pour des concepts plus élaborés sans être trop grand.",
    nl: "De Standard is ons meest gebouwde model: de gebalanceerde middenweg tussen ruimte, uitrustingsopties en prijs. Genoeg ruimte voor uitgebreidere concepten zonder onnodig groot te zijn.",
  },
  "Meistgewähltes Modell unserer Reihe": {
    de: "Meistgewähltes Modell unserer Reihe",
    en: "Most chosen model in our range",
    fr: "Modèle le plus choisi de notre gamme",
    nl: "Meest gekozen model uit onze reeks",
  },
  "Mehr Platz für Theke, Küche und Technik": {
    de: "Mehr Platz für Theke, Küche und Technik",
    en: "More space for counter, kitchen and equipment",
    fr: "Plus d'espace pour comptoir, cuisine et technique",
    nl: "Meer ruimte voor toonbank, keuken en techniek",
  },
  "Breite Auswahl an Fenster- und Ausstattungsvarianten": {
    de: "Breite Auswahl an Fenster- und Ausstattungsvarianten",
    en: "Wide choice of window and equipment variants",
    fr: "Large choix de variantes de fenêtres et d'équipement",
    nl: "Ruime keuze aan raam- en uitrustingsvarianten",
  },
  "Bewährte Bauweise, tausendfach im Einsatz": {
    de: "Bewährte Bauweise, tausendfach im Einsatz",
    en: "Proven build, used thousands of times",
    fr: "Construction éprouvée, utilisée des milliers de fois",
    nl: "Bewezen bouw, duizenden keren ingezet",
  },
  "Für hohe Ansprüche — mehr Ausstattung, mehr Auftritt.": {
    de: "Für hohe Ansprüche — mehr Ausstattung, mehr Auftritt.",
    en: "For higher standards — more equipment, more presence.",
    fr: "Pour des exigences élevées — plus d'équipement, plus de présence.",
    nl: "Voor hogere eisen — meer uitrusting, meer uitstraling.",
  },
  "Der Premium richtet sich an alle mit hohem Anspruch an Ausstattung und Auftritt — gleiche Grundfläche wie der Standard, aber mit hochwertigerer Verarbeitung und mehr Ausstattungsdetails ab Werk.": {
    de: "Der Premium richtet sich an alle mit hohem Anspruch an Ausstattung und Auftritt — gleiche Grundfläche wie der Standard, aber mit hochwertigerer Verarbeitung und mehr Ausstattungsdetails ab Werk.",
    en: "The Premium is for anyone with high expectations for equipment and appearance: the same footprint as the Standard, but with higher-grade finish and more equipment details from the factory.",
    fr: "Le Premium s'adresse à ceux qui exigent plus d'équipement et de présence : même surface que le Standard, mais finition plus haut de gamme et plus de détails d'équipement d'usine.",
    nl: "De Premium is voor wie hoge eisen stelt aan uitrusting en uitstraling: dezelfde basis als de Standard, maar met hoogwaardigere afwerking en meer uitrustingsdetails af fabriek.",
  },
  "Hochwertigere Verarbeitung und Materialien": {
    de: "Hochwertigere Verarbeitung und Materialien",
    en: "Higher-grade finish and materials",
    fr: "Finition et matériaux de qualité supérieure",
    nl: "Hoogwaardigere afwerking en materialen",
  },
  "Mehr Ausstattung bereits ab Werk enthalten": {
    de: "Mehr Ausstattung bereits ab Werk enthalten",
    en: "More equipment included from the factory",
    fr: "Plus d'équipements inclus d'usine",
    nl: "Meer uitrusting standaard inbegrepen",
  },
  "Repräsentativer Auftritt für dein Business": {
    de: "Repräsentativer Auftritt für dein Business",
    en: "A more representative presence for your business",
    fr: "Une présence plus représentative pour votre activité",
    nl: "Een representatievere uitstraling voor je bedrijf",
  },
  "Volle Flexibilität durch den Konfigurator": {
    de: "Volle Flexibilität durch den Konfigurator",
    en: "Full flexibility through the configurator",
    fr: "Flexibilité totale grâce au configurateur",
    nl: "Volledige flexibiliteit via de configurator",
  },
  "Variante A": { de: "Variante A", en: "Variant A", fr: "Variante A", nl: "Variant A" },
  "Variante B": { de: "Variante B", en: "Variant B", fr: "Variante B", nl: "Variant B" },
  "Variante C": { de: "Variante C", en: "Variant C", fr: "Variante C", nl: "Variant C" },
  "1 kleines Frontfenster, 1 Seitenfenster": {
    de: "1 kleines Frontfenster, 1 Seitenfenster",
    en: "1 small front window, 1 side window",
    fr: "1 petite fenêtre frontale, 1 fenêtre latérale",
    nl: "1 klein voorraam, 1 zijraam",
  },
  "2 kleine Frontfenster, 1 Seitenfenster": {
    de: "2 kleine Frontfenster, 1 Seitenfenster",
    en: "2 small front windows, 1 side window",
    fr: "2 petites fenêtres frontales, 1 fenêtre latérale",
    nl: "2 kleine voorramen, 1 zijraam",
  },
  "1 großes Frontfenster über die volle Breite": {
    de: "1 großes Frontfenster über die volle Breite",
    en: "1 large front window across the full width",
    fr: "1 grande fenêtre frontale sur toute la largeur",
    nl: "1 groot voorraam over de volledige breedte",
  },
  "1 Seite offen": { de: "1 Seite offen", en: "1 side open", fr: "1 côté ouvert", nl: "1 zijde open" },
  "2 Seiten offen": { de: "2 Seiten offen", en: "2 sides open", fr: "2 côtés ouverts", nl: "2 zijden open" },
  "3 Seiten offen": { de: "3 Seiten offen", en: "3 sides open", fr: "3 côtés ouverts", nl: "3 zijden open" },
  "Alle Seiten offen": { de: "Alle Seiten offen", en: "All sides open", fr: "Tous les côtés ouverts", nl: "Alle zijden open" },
  "Eine Verkaufsseite geöffnet, die übrigen Seiten geschlossen.": {
    de: "Eine Verkaufsseite geöffnet, die übrigen Seiten geschlossen.",
    en: "One sales side open, the remaining sides closed.",
    fr: "Un côté de vente ouvert, les autres côtés fermés.",
    nl: "Een verkoopzijde open, de overige zijden gesloten.",
  },
  "Zwei offene Seiten für Verkauf und Ausgabe über Eck.": {
    de: "Zwei offene Seiten für Verkauf und Ausgabe über Eck.",
    en: "Two open sides for corner sales and service.",
    fr: "Deux côtés ouverts pour vendre et servir en angle.",
    nl: "Twee open zijden voor verkoop en uitgifte om de hoek.",
  },
  "Drei Seiten offen für viel Sichtbarkeit und schnellen Zugang.": {
    de: "Drei Seiten offen für viel Sichtbarkeit und schnellen Zugang.",
    en: "Three sides open for high visibility and quick access.",
    fr: "Trois côtés ouverts pour plus de visibilité et un accès rapide.",
    nl: "Drie zijden open voor veel zichtbaarheid en snelle toegang.",
  },
  "Rundum offen für Markt, Event oder flexible Ausgabe.": {
    de: "Rundum offen für Markt, Event oder flexible Ausgabe.",
    en: "Open all around for markets, events or flexible service.",
    fr: "Ouvert tout autour pour marchés, événements ou service flexible.",
    nl: "Rondom open voor markten, events of flexibele uitgifte.",
  },
  "Kompakt für kleine Märkte, Events oder einen schnellen Einstieg.": {
    de: "Kompakt für kleine Märkte, Events oder einen schnellen Einstieg.",
    en: "Compact for small markets, events or a quick start.",
    fr: "Compact pour petits marchés, événements ou démarrage rapide.",
    nl: "Compact voor kleine markten, events of een snelle start.",
  },
  "Mehr Ausgabe- und Arbeitsfläche bei weiterhin einfachem Aufbau.": {
    de: "Mehr Ausgabe- und Arbeitsfläche bei weiterhin einfachem Aufbau.",
    en: "More service and work space while remaining easy to set up.",
    fr: "Plus d'espace de service et de travail, tout en restant simple à monter.",
    nl: "Meer uitgifte- en werkruimte, met eenvoudige opbouw.",
  },
  "Große Lösung für mehrere Mitarbeitende, viel Ware oder hohe Frequenz.": {
    de: "Große Lösung für mehrere Mitarbeitende, viel Ware oder hohe Frequenz.",
    en: "Large solution for several staff members, more stock or high traffic.",
    fr: "Grande solution pour plusieurs personnes, beaucoup de stock ou forte fréquentation.",
    nl: "Grote oplossing voor meerdere medewerkers, veel voorraad of hoge drukte.",
  },
  "Arbeitsfläche — Material": { de: "Arbeitsfläche — Material", en: "Work surface — material", fr: "Plan de travail — matériau", nl: "Werkblad — materiaal" },
  "Arbeitsfläche — Umfang": { de: "Arbeitsfläche — Umfang", en: "Work surface — scope", fr: "Plan de travail — étendue", nl: "Werkblad — omvang" },
  "Edelstahl ist robuster und wirkt hochwertiger; HPL ist leichter und günstiger.": {
    de: "Edelstahl ist robuster und wirkt hochwertiger; HPL ist leichter und günstiger.",
    en: "Stainless steel is more robust and premium; HPL is lighter and more affordable.",
    fr: "L'inox est plus robuste et plus qualitatif ; le HPL est plus léger et moins cher.",
    nl: "RVS is robuuster en oogt hoogwaardiger; HPL is lichter en voordeliger.",
  },
  "Wähle ungefähr, wie viel Arbeitsfläche du brauchst.": {
    de: "Wähle ungefähr, wie viel Arbeitsfläche du brauchst.",
    en: "Choose roughly how much work surface you need.",
    fr: "Choisissez approximativement la surface de travail nécessaire.",
    nl: "Kies ongeveer hoeveel werkruimte je nodig hebt.",
  },
  "Stromversorgung": { de: "Stromversorgung", en: "Power supply", fr: "Alimentation électrique", nl: "Stroomvoorziening" },
  "Optional mit Strominsel, Starkstromkabel oder vorbereitetem Anschluss.": {
    de: "Optional mit Strominsel, Starkstromkabel oder vorbereitetem Anschluss.",
    en: "Optional with power hub, three-phase cable or prepared connection.",
    fr: "En option avec îlot électrique, câble triphasé ou raccordement préparé.",
    nl: "Optioneel met stroompunt, krachtstroomkabel of voorbereide aansluiting.",
  },
  "Individualisierung": { de: "Individualisierung", en: "Customization", fr: "Personnalisation", nl: "Personalisatie" },
  "Grundlage für Logo, Farbe oder Bedruckung. Eine Datei kannst du unten zusätzlich hochladen.": {
    de: "Grundlage für Logo, Farbe oder Bedruckung. Eine Datei kannst du unten zusätzlich hochladen.",
    en: "Basis for logo, color or print. You can also upload a file below.",
    fr: "Base pour logo, couleur ou impression. Vous pouvez aussi téléverser un fichier plus bas.",
    nl: "Basis voor logo, kleur of bedrukking. Je kunt hieronder ook een bestand uploaden.",
  },
  "Äußere Fenster": { de: "Äußere Fenster", en: "Exterior windows", fr: "Fenêtres extérieures", nl: "Buitenramen" },
  "Äußere Türen": { de: "Äußere Türen", en: "Exterior doors", fr: "Portes extérieures", nl: "Buitendeuren" },
  "Aufbau des Fahrgestells": { de: "Aufbau des Fahrgestells", en: "Chassis structure", fr: "Structure du châssis", nl: "Opbouw van het chassis" },
  "Elektroinstallation": { de: "Elektroinstallation", en: "Electrical installation", fr: "Installation électrique", nl: "Elektrische installatie" },
  "Installation — Hydraulik": { de: "Installation — Hydraulik", en: "Installation — water system", fr: "Installation — hydraulique", nl: "Installatie — water" },
  "Innenausstattung — Möbelaufbau": { de: "Innenausstattung — Möbelaufbau", en: "Interior — furniture build", fr: "Intérieur — mobilier", nl: "Interieur — meubelopbouw" },
  "Innenausbau — Haushaltsgeräte": { de: "Innenausbau — Haushaltsgeräte", en: "Interior — appliances", fr: "Aménagement — appareils", nl: "Interieur — apparaten" },
  "Fassade": { de: "Fassade", en: "Facade", fr: "Façade", nl: "Gevel" },
  "Branding — Logo": { de: "Branding — Logo", en: "Branding — logo", fr: "Branding — logo", nl: "Branding — logo" },
  "Branding — Menü": { de: "Branding — Menü", en: "Branding — menu", fr: "Branding — menu", nl: "Branding — menu" },
  "Zusätzliche Ausstattung — Überwachung": { de: "Zusätzliche Ausstattung — Überwachung", en: "Additional equipment — surveillance", fr: "Équipement supplémentaire — surveillance", nl: "Extra uitrusting — bewaking" },
  "Edelstahltische": { de: "Edelstahltische", en: "Stainless steel tables", fr: "Tables inox", nl: "RVS tafels" },
  "HPL-Hygieneplatten": { de: "HPL-Hygieneplatten", en: "HPL hygiene panels", fr: "Panneaux hygiène HPL", nl: "HPL-hygiëneplaten" },
  "nach Bedarf planen": { de: "nach Bedarf planen", en: "plan as needed", fr: "planifier selon besoin", nl: "naar behoefte plannen" },
  "Keine Zusatzlösung": { de: "Keine Zusatzlösung", en: "No extra solution", fr: "Pas de solution supplémentaire", nl: "Geen extra oplossing" },
  "Strominsel 230 V": { de: "Strominsel 230 V", en: "230 V power hub", fr: "Îlot électrique 230 V", nl: "230 V stroompunt" },
  "Starkstrom vorbereitet": { de: "Starkstrom vorbereitet", en: "Three-phase prepared", fr: "Triphasé préparé", nl: "Krachtstroom voorbereid" },
  "Starkstromkabel inklusive": { de: "Starkstromkabel inklusive", en: "Three-phase cable included", fr: "Câble triphasé inclus", nl: "Krachtstroomkabel inbegrepen" },
  "Ohne Branding": { de: "Ohne Branding", en: "No branding", fr: "Sans branding", nl: "Zonder branding" },
  "Logo auf Plane": { de: "Logo auf Plane", en: "Logo on tarp", fr: "Logo sur bâche", nl: "Logo op zeil" },
  "vollflächige Gestaltung": { de: "vollflächige Gestaltung", en: "Full-surface design", fr: "Design pleine surface", nl: "Volledig ontwerp" },
  "Keine Gläser": { de: "Keine Gläser", en: "No glass panels", fr: "Pas de vitrages", nl: "Geen glas" },
  "Schiebegläser": { de: "Schiebegläser", en: "Sliding glass panels", fr: "Vitrages coulissants", nl: "Schuiframen" },
  "Volltüren": { de: "Volltüren", en: "Solid doors", fr: "Portes pleines", nl: "Volle deuren" },
  "Türen mit Fenster": { de: "Türen mit Fenster", en: "Doors with window", fr: "Portes avec fenêtre", nl: "Deuren met raam" },
  "Kein Aufbau": { de: "Kein Aufbau", en: "No structure", fr: "Pas de structure", nl: "Geen opbouw" },
  "Sockel (Abdeckung)": { de: "Sockel (Abdeckung)", en: "Base cover", fr: "Socle cache", nl: "Sokkelafdekking" },
  "Keine": { de: "Keine", en: "None", fr: "Aucun", nl: "Geen" },
  "Geschlossen": { de: "Geschlossen", en: "Closed", fr: "Fermé", nl: "Gesloten" },
  "Offener Wasserkreislauf": { de: "Offener Wasserkreislauf", en: "Open water circuit", fr: "Circuit d'eau ouvert", nl: "Open watercircuit" },
  "Stock (ohne Möbel)": { de: "Stock (ohne Möbel)", en: "Stock without furniture", fr: "Brut sans mobilier", nl: "Stock zonder meubels" },
  "Street-Food Konzept süß": { de: "Street-Food Konzept süß", en: "Sweet street-food concept", fr: "Concept street food sucré", nl: "Zoet streetfoodconcept" },
  "Street-Food Konzept herzhaft": { de: "Street-Food Konzept herzhaft", en: "Savory street-food concept", fr: "Concept street food salé", nl: "Hartig streetfoodconcept" },
  "Zum Beispiel Kühlschrank, Grill oder eine schlüsselfertige Küchenausstattung": {
    de: "Zum Beispiel Kühlschrank, Grill oder eine schlüsselfertige Küchenausstattung",
    en: "For example refrigerator, grill or a turnkey kitchen setup",
    fr: "Par exemple réfrigérateur, grill ou équipement cuisine clé en main",
    nl: "Bijvoorbeeld koelkast, grill of een kant-en-klare keukenuitrusting",
  },
  "Kühlschrank": { de: "Kühlschrank", en: "Refrigerator", fr: "Réfrigérateur", nl: "Koelkast" },
  "Kühlschrank + Grill": { de: "Kühlschrank + Grill", en: "Refrigerator + grill", fr: "Réfrigérateur + grill", nl: "Koelkast + grill" },
  "Ohne Dibond": { de: "Ohne Dibond", en: "Without Dibond", fr: "Sans Dibond", nl: "Zonder Dibond" },
  "Kein Logo": { de: "Kein Logo", en: "No logo", fr: "Pas de logo", nl: "Geen logo" },
  "Premium (beleuchtet)": { de: "Premium (beleuchtet)", en: "Premium illuminated", fr: "Premium éclairé", nl: "Premium verlicht" },
  "Kein Menü": { de: "Kein Menü", en: "No menu", fr: "Pas de menu", nl: "Geen menu" },
  "1 Kamera": { de: "1 Kamera", en: "1 camera", fr: "1 caméra", nl: "1 camera" },
  "2 Kameras": { de: "2 Kameras", en: "2 cameras", fr: "2 caméras", nl: "2 camera's" },
  "Eigenes Paket": { de: "Eigenes Paket", en: "Custom package", fr: "Pack personnalisé", nl: "Eigen pakket" },
  "Du stellst die Geräte selbst zusammen.": { de: "Du stellst die Geräte selbst zusammen.", en: "You assemble the equipment yourself.", fr: "Vous composez vous-même l'équipement.", nl: "Je stelt de apparaten zelf samen." },
  "nach Auswahl": { de: "nach Auswahl", en: "based on selection", fr: "selon sélection", nl: "volgens keuze" },
  "Freie Geräteauswahl": { de: "Freie Geräteauswahl", en: "Free equipment selection", fr: "Choix libre des appareils", nl: "Vrije apparaatkeuze" },
  "Individuelle Planung": { de: "Individuelle Planung", en: "Individual planning", fr: "Planification individuelle", nl: "Individuele planning" },
  "Angebot nach Bedarf": { de: "Angebot nach Bedarf", en: "Quote as needed", fr: "Offre selon besoin", nl: "Offerte naar behoefte" },
  "Pommes Laden": { de: "Pommes Laden", en: "Fries shop", fr: "Stand frites", nl: "Frietzaak" },
  "Für Fritten, Snacks und schnelle Ausgabe.": { de: "Für Fritten, Snacks und schnelle Ausgabe.", en: "For fries, snacks and quick service.", fr: "Pour frites, snacks et service rapide.", nl: "Voor friet, snacks en snelle uitgifte." },
  "Pizza": { de: "Pizza", en: "Pizza", fr: "Pizza", nl: "Pizza" },
  "Für Pizza, Flammkuchen oder ähnliche Ofen-Konzepte.": { de: "Für Pizza, Flammkuchen oder ähnliche Ofen-Konzepte.", en: "For pizza, tarte flambée or similar oven concepts.", fr: "Pour pizza, flammekueche ou concepts au four similaires.", nl: "Voor pizza, flammkuchen of vergelijkbare ovenconcepten." },
  "Würstchen": { de: "Würstchen", en: "Sausages", fr: "Saucisses", nl: "Worstjes" },
  "Für Grill, Bratwurst und klassische Imbiss-Ausgabe.": { de: "Für Grill, Bratwurst und klassische Imbiss-Ausgabe.", en: "For grill, bratwurst and classic snack service.", fr: "Pour grill, bratwurst et service snack classique.", nl: "Voor grill, braadworst en klassieke snackuitgifte." },
  "Getränke": { de: "Getränke", en: "Drinks", fr: "Boissons", nl: "Dranken" },
  "Für kalte Getränke, Kaffee oder Ausschank.": { de: "Für kalte Getränke, Kaffee oder Ausschank.", en: "For cold drinks, coffee or bar service.", fr: "Pour boissons froides, café ou débit de boissons.", nl: "Voor koude dranken, koffie of tapservice." },
  "Eis": { de: "Eis", en: "Ice cream", fr: "Glaces", nl: "IJs" },
  "Für Eisverkauf und gekühlte Produkte.": { de: "Für Eisverkauf und gekühlte Produkte.", en: "For ice cream sales and chilled products.", fr: "Pour vente de glaces et produits frais.", nl: "Voor ijsverkoop en gekoelde producten." },
  "Fritteuse": { de: "Fritteuse", en: "Fryer", fr: "Friteuse", nl: "Friteuse" },
  "Kühlung": { de: "Kühlung", en: "Cooling", fr: "Réfrigération", nl: "Koeling" },
  "Warmhaltung": { de: "Warmhaltung", en: "Warming station", fr: "Maintien au chaud", nl: "Warmhoudapparatuur" },
  "Edelstahl-Arbeitsfläche": { de: "Edelstahl-Arbeitsfläche", en: "Stainless steel work surface", fr: "Plan de travail inox", nl: "RVS werkblad" },
  "Pizzaofen": { de: "Pizzaofen", en: "Pizza oven", fr: "Four à pizza", nl: "Pizzaoven" },
  "Pizzakühlung": { de: "Pizzakühlung", en: "Pizza cooling unit", fr: "Réfrigération pizza", nl: "Pizzakoeling" },
  "Abluft": { de: "Abluft", en: "Exhaust air", fr: "Extraction", nl: "Afzuiging" },
  "Grill": { de: "Grill", en: "Grill", fr: "Grill", nl: "Grill" },
  "Getränkekühler": { de: "Getränkekühler", en: "Drinks cooler", fr: "Réfrigérateur à boissons", nl: "Drankenkoeler" },
  "Stauraum": { de: "Stauraum", en: "Storage space", fr: "Rangement", nl: "Opbergruimte" },
  "Eistruhe": { de: "Eistruhe", en: "Ice cream freezer", fr: "Congélateur à glaces", nl: "IJsvriezer" },
  "Portionierbereich": { de: "Portionierbereich", en: "Serving area", fr: "Zone de portionnement", nl: "Portioneerzone" },
  "Geräte & Ausstattung": { de: "Geräte & Ausstattung", en: "Equipment & fittings", fr: "Équipement & aménagement", nl: "Apparaten & uitrusting" },
  "Optional: ergänze ein Paket oder erstelle dein eigenes Küchenkonzept. Eine Spüle ist immer inklusive.": {
    de: "Optional: ergänze ein Paket oder erstelle dein eigenes Küchenkonzept. Eine Spüle ist immer inklusive.",
    en: "Optional: add a package or create your own kitchen concept. A sink is always included.",
    fr: "Optionnel : ajoutez un pack ou créez votre propre concept cuisine. Un évier est toujours inclus.",
    nl: "Optioneel: voeg een pakket toe of maak je eigen keukenconcept. Een spoelbak is altijd inbegrepen.",
  },
  "Zusätzliche Dienstleistungen (optional)": { de: "Zusätzliche Dienstleistungen (optional)", en: "Additional services (optional)", fr: "Services supplémentaires (optionnel)", nl: "Extra diensten (optioneel)" },
  "Transport": { de: "Transport", en: "Transport", fr: "Transport", nl: "Transport" },
  "Montage": { de: "Montage", en: "Assembly", fr: "Montage", nl: "Montage" },
  "Einweisung": { de: "Einweisung", en: "Handover briefing", fr: "Formation à la prise en main", nl: "Instructie" },
  "Ikonisch": { de: "Ikonisch", en: "Iconic", fr: "Iconique", nl: "Iconisch" },
  "Ikonische": { de: "Ikonische", en: "Iconic", fr: "Iconiques", nl: "Iconische" },
  "Modelle": { de: "Modelle", en: "Models", fr: "Modèles", nl: "Modellen" },
  "Modelle.": { de: "Modelle.", en: "Models.", fr: "Modèles.", nl: "Modellen." },
  "Zeitloses Design + handwerkliche Qualität": {
    de: "Zeitloses Design + handwerkliche Qualität",
    en: "Timeless design + craft quality",
    fr: "Design intemporel + qualité artisanale",
    nl: "Tijdloos design + ambachtelijke kwaliteit",
  },
  "Ein MINO ist mehr als ein Verkaufsanhänger — er ist die Bühne für dein Konzept, gebaut für Alltag, Wirkung und lange Nutzung.": {
    de: "Ein MINO ist mehr als ein Verkaufsanhänger — er ist die Bühne für dein Konzept, gebaut für Alltag, Wirkung und lange Nutzung.",
    en: "A MINO is more than a sales trailer: it is the stage for your concept, built for daily use, impact and long-term value.",
    fr: "Un MINO est plus qu'une remorque de vente : c'est la scène de votre concept, conçu pour le quotidien, l'impact et la durée.",
    nl: "Een MINO is meer dan een verkooptrailer: het is het podium voor je concept, gebouwd voor dagelijks gebruik, uitstraling en lange levensduur.",
  },
  "Vorheriges Modell": { de: "Vorheriges Modell", en: "Previous model", fr: "Modèle précédent", nl: "Vorig model" },
  "Nächstes Modell": { de: "Nächstes Modell", en: "Next model", fr: "Modèle suivant", nl: "Volgend model" },
  "Vier Grundformen, eine Handschrift — jedes Modell lässt sich im Konfigurator weiter auf dich zuschneiden.": {
    de: "Vier Grundformen, eine Handschrift — jedes Modell lässt sich im Konfigurator weiter auf dich zuschneiden.",
    en: "Four base shapes, one signature: every model can be tailored further in the configurator.",
    fr: "Quatre formes de base, une même signature : chaque modèle peut être adapté dans le configurateur.",
    nl: "Vier basisvormen, een herkenbare lijn: elk model kun je verder aanpassen in de configurator.",
  },
  "Vier Modelle. Eine Handschrift.": {
    de: "Vier Modelle. Eine Handschrift.",
    en: "Four models. One signature.",
    fr: "Quatre modèles. Une signature.",
    nl: "Vier modellen. Een herkenbare lijn.",
  },
  "Alle Modelle": { de: "Alle Modelle", en: "All models", fr: "Tous les modèles", nl: "Alle modellen" },
  "Modell im Detail ansehen": { de: "Modell im Detail ansehen", en: "View model details", fr: "Voir le modèle en détail", nl: "Model in detail bekijken" },
  "Beratung anfragen": { de: "Beratung anfragen", en: "Request consultation", fr: "Demander conseil", nl: "Advies aanvragen" },
  "Dein nächster Schritt": { de: "Dein nächster Schritt", en: "Your next step", fr: "Votre prochaine étape", nl: "Jouw volgende stap" },
  "Der Prozess": { de: "Der Prozess", en: "The process", fr: "Le processus", nl: "Het proces" },
  "Weitere Modelle": { de: "Weitere Modelle", en: "More models", fr: "Autres modèles", nl: "Meer modellen" },
  "Wir gehen den Weg": { de: "Wir gehen den Weg", en: "We take the path", fr: "Nous avançons", nl: "We gaan de weg" },
  "gemeinsam": { de: "gemeinsam", en: "together", fr: "ensemble", nl: "samen" },
  "Von deiner Entscheidung bis zur Übergabe.": {
    de: "Von deiner Entscheidung bis zur Übergabe.",
    en: "From your decision through to handover.",
    fr: "De votre décision jusqu'à la remise.",
    nl: "Van je beslissing tot aan de overdracht.",
  },
  "Station 01": { de: "Station 01", en: "Station 01", fr: "Étape 01", nl: "Station 01" },
  "Station 02": { de: "Station 02", en: "Station 02", fr: "Étape 02", nl: "Station 02" },
  "Station 03": { de: "Station 03", en: "Station 03", fr: "Étape 03", nl: "Station 03" },
  "Station 04": { de: "Station 04", en: "Station 04", fr: "Étape 04", nl: "Station 04" },
  "Rahmen": { de: "Rahmen", en: "Frame", fr: "Cadre", nl: "Frame" },
  "Aufbau": { de: "Aufbau", en: "Body", fr: "Structure", nl: "Opbouw" },
  "Innenausbau": { de: "Innenausbau", en: "Interior fit-out", fr: "Aménagement intérieur", nl: "Interieurafbouw" },
  "Technik": { de: "Technik", en: "Systems", fr: "Technique", nl: "Techniek" },
  "Theke": { de: "Theke", en: "Counter", fr: "Comptoir", nl: "Toonbank" },
  "Fertigstellung": { de: "Fertigstellung", en: "Completion", fr: "Finition", nl: "Afronding" },
  "Du entscheidest": { de: "Du entscheidest", en: "You decide", fr: "Vous décidez", nl: "Jij beslist" },
  "Fertig ab Lager oder ganz nach Maß": {
    de: "Fertig ab Lager oder ganz nach Maß",
    en: "Ready from stock or fully made to measure",
    fr: "Prêt en stock ou entièrement sur mesure",
    nl: "Klaar uit voorraad of volledig op maat",
  },
  "Wähle eines unserer Standardmodelle oder stelle deinen Anhänger im Konfigurator Schritt für Schritt selbst zusammen.": {
    de: "Wähle eines unserer Standardmodelle oder stelle deinen Anhänger im Konfigurator Schritt für Schritt selbst zusammen.",
    en: "Choose one of our standard models or configure your trailer step by step.",
    fr: "Choisissez l'un de nos modèles standard ou configurez votre remorque étape par étape.",
    nl: "Kies een van onze standaardmodellen of stel je trailer stap voor stap samen.",
  },
  "Zum Konfigurator": { de: "Zum Konfigurator", en: "Go to configurator", fr: "Vers le configurateur", nl: "Naar de configurator" },
  "Wir finalisieren dein Design": { de: "Wir finalisieren dein Design", en: "We finalize your design", fr: "Nous finalisons votre design", nl: "Wij finaliseren je ontwerp" },
  "Aus deiner Auswahl wird ein fertiges Modell": {
    de: "Aus deiner Auswahl wird ein fertiges Modell",
    en: "Your selection becomes a finished model",
    fr: "Votre sélection devient un modèle fini",
    nl: "Je keuze wordt een afgewerkt model",
  },
  "Wir stimmen die Details ab, planen die Umsetzung und halten dich während des gesamten Prozesses auf dem Laufenden.": {
    de: "Wir stimmen die Details ab, planen die Umsetzung und halten dich während des gesamten Prozesses auf dem Laufenden.",
    en: "We align the details, plan the build and keep you updated throughout the process.",
    fr: "Nous validons les détails, planifions la réalisation et vous tenons informé tout au long du processus.",
    nl: "We stemmen de details af, plannen de uitvoering en houden je tijdens het hele proces op de hoogte.",
  },
  "Wir halten dich auf dem Laufenden": { de: "Wir halten dich auf dem Laufenden", en: "We keep you updated", fr: "Nous vous tenons informé", nl: "We houden je op de hoogte" },
  "Transparente Updates während der Umsetzung": {
    de: "Transparente Updates während der Umsetzung",
    en: "Transparent updates during the build",
    fr: "Des mises à jour transparentes pendant la réalisation",
    nl: "Transparante updates tijdens de uitvoering",
  },
  "Du siehst, wo dein Anhänger gerade steht, welche Schritte abgeschlossen sind und was als Nächstes passiert.": {
    de: "Du siehst, wo dein Anhänger gerade steht, welche Schritte abgeschlossen sind und was als Nächstes passiert.",
    en: "You see where your trailer stands, which steps are complete and what happens next.",
    fr: "Vous voyez où en est votre remorque, quelles étapes sont terminées et ce qui vient ensuite.",
    nl: "Je ziet waar je trailer staat, welke stappen klaar zijn en wat er daarna gebeurt.",
  },
  "Du bekommst einen Anhänger": { de: "Du bekommst einen Anhänger", en: "You receive your trailer", fr: "Vous recevez votre remorque", nl: "Je ontvangt je trailer" },
  "Startklar für dein Geschäft": {
    de: "Startklar für dein Geschäft",
    en: "Ready for your business",
    fr: "Prêt pour votre activité",
    nl: "Klaar voor je bedrijf",
  },
  "Du bekommst deinen fertigen Imbisswagen inklusive Einweisung in Technik und Wartung übergeben.": {
    de: "Du bekommst deinen fertigen Imbisswagen inklusive Einweisung in Technik und Wartung übergeben.",
    en: "You receive your finished food trailer including a briefing on systems and maintenance.",
    fr: "Vous recevez votre remorque snack terminée avec une prise en main technique et maintenance.",
    nl: "Je ontvangt je afgewerkte foodtrailer inclusief uitleg over techniek en onderhoud.",
  },
  "Häufige": { de: "Häufige", en: "Frequently asked", fr: "Questions", nl: "Veelgestelde" },
  "Fragen": { de: "Fragen", en: "questions", fr: "fréquentes", nl: "vragen" },
  "Die wichtigsten Antworten, bevor aus deiner Idee ein fertiger Anhänger wird.": {
    de: "Die wichtigsten Antworten, bevor aus deiner Idee ein fertiger Anhänger wird.",
    en: "The key answers before your idea becomes a finished trailer.",
    fr: "Les réponses essentielles avant que votre idée devienne une remorque terminée.",
    nl: "De belangrijkste antwoorden voordat je idee een afgewerkte trailer wordt.",
  },
  "Wie lange dauert die Fertigung?": { de: "Wie lange dauert die Fertigung?", en: "How long does production take?", fr: "Combien de temps dure la fabrication ?", nl: "Hoe lang duurt de productie?" },
  "Typischerweise dauert die Fertigung eines MINO-Anhängers etwa 10 bis 14 Wochen.": {
    de: "Typischerweise dauert die Fertigung eines MINO-Anhängers etwa 10 bis 14 Wochen.",
    en: "Production of a MINO trailer typically takes around 10 to 14 weeks.",
    fr: "La fabrication d'une remorque MINO prend généralement environ 10 à 14 semaines.",
    nl: "De productie van een MINO-trailer duurt meestal ongeveer 10 tot 14 weken.",
  },
  "Kann ich meinen Anhänger individuell gestalten?": { de: "Kann ich meinen Anhänger individuell gestalten?", en: "Can I customize my trailer?", fr: "Puis-je personnaliser ma remorque ?", nl: "Kan ik mijn trailer individueel aanpassen?" },
  "Ja. Unsere Anhänger sind auf Basis der Modelle nahezu vollständig individualisierbar.": {
    de: "Ja. Unsere Anhänger sind auf Basis der Modelle nahezu vollständig individualisierbar.",
    en: "Yes. Our trailers can be customized almost completely based on the models.",
    fr: "Oui. Nos remorques sont presque entièrement personnalisables à partir des modèles.",
    nl: "Ja. Onze trailers zijn op basis van de modellen vrijwel volledig aanpasbaar.",
  },
  "Bietet ihr Lieferung an?": { de: "Bietet ihr Lieferung an?", en: "Do you offer delivery?", fr: "Proposez-vous la livraison ?", nl: "Bieden jullie levering aan?" },
  "Ja, die Lieferung bieten wir mit an und stimmen den Ablauf passend mit dir ab.": {
    de: "Ja, die Lieferung bieten wir mit an und stimmen den Ablauf passend mit dir ab.",
    en: "Yes, we can provide delivery and coordinate the process with you.",
    fr: "Oui, nous pouvons organiser la livraison et coordonner le déroulement avec vous.",
    nl: "Ja, we bieden levering aan en stemmen de planning met je af.",
  },
  "Ist der TÜV inklusive?": { de: "Ist der TÜV inklusive?", en: "Is TÜV approval included?", fr: "Le contrôle TÜV est-il inclus ?", nl: "Is de TÜV-keuring inbegrepen?" },
  "Ja. Der TÜV ist bei deinem fertigen Anhänger inklusive.": {
    de: "Ja. Der TÜV ist bei deinem fertigen Anhänger inklusive.",
    en: "Yes. TÜV approval is included with your finished trailer.",
    fr: "Oui. Le TÜV est inclus avec votre remorque terminée.",
    nl: "Ja. De TÜV-keuring is inbegrepen bij je afgewerkte trailer.",
  },
  "Gibt es auch fertige Produkte?": { de: "Gibt es auch fertige Produkte?", en: "Are ready-made products available?", fr: "Existe-t-il aussi des produits prêts ?", nl: "Zijn er ook kant-en-klare producten?" },
  "Ja. Verfügbare Imbiss-Anhänger und Pavillons findest du unter Sofort verfügbar oder Mieten.": {
    de: "Ja. Verfügbare Imbiss-Anhänger und Pavillons findest du unter Sofort verfügbar oder Mieten.",
    en: "Yes. Available food trailers and pavilions are listed under Available now or Rent.",
    fr: "Oui. Les remorques snack et pavillons disponibles se trouvent sous Disponible maintenant ou Louer.",
    nl: "Ja. Beschikbare foodtrailers en paviljoens vind je onder Direct beschikbaar of Huren.",
  },
  "Wie startet der Prozess?": { de: "Wie startet der Prozess?", en: "How does the process start?", fr: "Comment démarre le processus ?", nl: "Hoe start het proces?" },
  "Du wählst ein Modell, konfigurierst deinen Anhänger oder fragst direkt eine Beratung an.": {
    de: "Du wählst ein Modell, konfigurierst deinen Anhänger oder fragst direkt eine Beratung an.",
    en: "You choose a model, configure your trailer or request a consultation directly.",
    fr: "Vous choisissez un modèle, configurez votre remorque ou demandez directement conseil.",
    nl: "Je kiest een model, configureert je trailer of vraagt direct advies aan.",
  },
  "Bereit,": { de: "Bereit,", en: "Ready", fr: "Prêt", nl: "Klaar" },
  "deinen Traum zu verwirklichen?": {
    de: "deinen Traum zu verwirklichen?",
    en: "to make your dream real?",
    fr: "à concrétiser votre rêve ?",
    nl: "om je droom waar te maken?",
  },
  "Konfiguriere jetzt deinen Anhänger oder lass dich unverbindlich beraten.": {
    de: "Konfiguriere jetzt deinen Anhänger oder lass dich unverbindlich beraten.",
    en: "Configure your trailer now or get a non-binding consultation.",
    fr: "Configurez votre remorque maintenant ou demandez un conseil sans engagement.",
    nl: "Configureer nu je trailer of vraag vrijblijvend advies aan.",
  },
  "Jetzt konfigurieren": { de: "Jetzt konfigurieren", en: "Configure now", fr: "Configurer", nl: "Nu configureren" },
  "Beratung zu einem Modell": { de: "Beratung zu einem Modell", en: "Consultation for a model", fr: "Conseil sur un modèle", nl: "Advies over een model" },
  "Fertiger Anhänger": { de: "Fertiger Anhänger", en: "Finished trailer", fr: "Remorque prête", nl: "Afgewerkte trailer" },
  "Konfigurator-Frage": { de: "Konfigurator-Frage", en: "Configurator question", fr: "Question sur le configurateur", nl: "Vraag over de configurator" },
  "Sonstiges": { de: "Sonstiges", en: "Other", fr: "Autre", nl: "Overig" },
  "Anliegen": { de: "Anliegen", en: "Subject", fr: "Objet", nl: "Onderwerp" },
  "Nachricht *": { de: "Nachricht *", en: "Message *", fr: "Message *", nl: "Bericht *" },
  "Wie können wir dir helfen?": { de: "Wie können wir dir helfen?", en: "How can we help?", fr: "Comment pouvons-nous vous aider ?", nl: "Hoe kunnen we je helpen?" },
  "Nachricht senden": { de: "Nachricht senden", en: "Send message", fr: "Envoyer le message", nl: "Bericht verzenden" },
  "Öffnet dein E-Mail-Programm mit vorausgefüllter Nachricht.": {
    de: "Öffnet dein E-Mail-Programm mit vorausgefüllter Nachricht.",
    en: "Opens your email app with a pre-filled message.",
    fr: "Ouvre votre application e-mail avec un message prérempli.",
    nl: "Opent je e-mailprogramma met een vooraf ingevuld bericht.",
  },
  "Dein E-Mail-Programm sollte sich gerade geöffnet haben — bitte sende die Nachricht dort ab.": {
    de: "Dein E-Mail-Programm sollte sich gerade geöffnet haben — bitte sende die Nachricht dort ab.",
    en: "Your email app should have opened — please send the message there.",
    fr: "Votre application e-mail devrait être ouverte — veuillez y envoyer le message.",
    nl: "Je e-mailprogramma zou nu geopend moeten zijn — verstuur het bericht daar.",
  },
  "Lass uns": { de: "Lass uns", en: "Let's", fr: "Parlons", nl: "Laten we" },
  "sprechen.": { de: "sprechen.", en: "talk.", fr: "ensemble.", nl: "praten." },
  "Ob Beratung, Frage zum Modell oder Anfrage zu deinem fertigen Anhänger — schreib uns, wir melden uns zeitnah zurück.": {
    de: "Ob Beratung, Frage zum Modell oder Anfrage zu deinem fertigen Anhänger — schreib uns, wir melden uns zeitnah zurück.",
    en: "Whether you need advice, have a model question or want to request a finished trailer, write to us and we will get back to you soon.",
    fr: "Conseil, question sur un modèle ou demande pour une remorque prête : écrivez-nous, nous vous répondrons rapidement.",
    nl: "Of het nu om advies, een modelvraag of een aanvraag voor een afgewerkte trailer gaat: stuur ons een bericht, we reageren snel.",
  },
  "Direkt erreichbar": { de: "Direkt erreichbar", en: "Reach us directly", fr: "Contact direct", nl: "Direct bereikbaar" },
  "Erreichbarkeit": { de: "Erreichbarkeit", en: "Availability", fr: "Disponibilité", nl: "Bereikbaarheid" },
  "Sofort verfügbar": { de: "Sofort verfügbar", en: "Available now", fr: "Disponible maintenant", nl: "Direct beschikbaar" },
  "In Fertigung": { de: "In Fertigung", en: "In production", fr: "En fabrication", nl: "In productie" },
  "Reservierbar": { de: "Reservierbar", en: "Reservable", fr: "Réservable", nl: "Reserveerbaar" },
  "Mietbereit": { de: "Mietbereit", en: "Ready to rent", fr: "Prêt à louer", nl: "Klaar voor verhuur" },
  "Auf Anfrage": { de: "Auf Anfrage", en: "On request", fr: "Sur demande", nl: "Op aanvraag" },
  "Modell / Variante": { de: "Modell / Variante", en: "Model / variant", fr: "Modèle / variante", nl: "Model / variant" },
  "Länge / Fläche": { de: "Länge / Fläche", en: "Length / area", fr: "Longueur / surface", nl: "Lengte / oppervlakte" },
  "Länge": { de: "Länge", en: "Length", fr: "Longueur", nl: "Lengte" },
  "Gewicht": { de: "Gewicht", en: "Weight", fr: "Poids", nl: "Gewicht" },
  "Preis": { de: "Preis", en: "Price", fr: "Prix", nl: "Prijs" },
  "bis 2 M": { de: "bis 2 M", en: "up to 2 m", fr: "jusqu'à 2 m", nl: "tot 2 m" },
  "bis 750 KG": { de: "bis 750 KG", en: "up to 750 kg", fr: "jusqu'à 750 kg", nl: "tot 750 kg" },
  "bis 15.000 €": { de: "bis 15.000 €", en: "up to €15,000", fr: "jusqu'à 15 000 €", nl: "tot €15.000" },
  "bis 25.000 €": { de: "bis 25.000 €", en: "up to €25,000", fr: "jusqu'à 25 000 €", nl: "tot €25.000" },
  "15.000 - 25.000 €": { de: "15.000 - 25.000 €", en: "€15,000 - €25,000", fr: "15 000 - 25 000 €", nl: "€15.000 - €25.000" },
  "25.000–35.000 €": { de: "25.000–35.000 €", en: "€25,000–€35,000", fr: "25 000–35 000 €", nl: "€25.000–€35.000" },
  "ab 25.000 €": { de: "ab 25.000 €", en: "from €25,000", fr: "à partir de 25 000 €", nl: "vanaf €25.000" },
  "über 35.000 €": { de: "über 35.000 €", en: "over €35,000", fr: "plus de 35 000 €", nl: "meer dan €35.000" },
  "bis 2 t": { de: "bis 2 t", en: "up to 2 t", fr: "jusqu'à 2 t", nl: "tot 2 t" },
  "2–3 t": { de: "2–3 t", en: "2–3 t", fr: "2–3 t", nl: "2–3 t" },
  "über 3 t": { de: "über 3 t", en: "over 3 t", fr: "plus de 3 t", nl: "meer dan 3 t" },
  "bald": { de: "bald", en: "soon", fr: "bientôt", nl: "binnenkort" },
  "Anhänger verfügbar": { de: "Anhänger verfügbar", en: "trailers available", fr: "remorques disponibles", nl: "trailers beschikbaar" },
  "Für diese Filterkombination ist aktuell kein Anhänger verfügbar.": {
    de: "Für diese Filterkombination ist aktuell kein Anhänger verfügbar.",
    en: "No trailer is currently available for this filter combination.",
    fr: "Aucune remorque n'est actuellement disponible pour cette combinaison de filtres.",
    nl: "Voor deze filtercombinatie is momenteel geen trailer beschikbaar.",
  },
  "Sofort verfügbarer Imbiss-Anhänger, 5 M, 1,5 T": {
    de: "Sofort verfügbarer Imbiss-Anhänger, 5 M, 1,5 T",
    en: "Available now food trailer, 5 m, 1.5 t",
    fr: "Remorque snack disponible maintenant, 5 m, 1,5 t",
    nl: "Direct beschikbare foodtrailer, 5 m, 1,5 t",
  },
  "Günstiger Verkaufs-Pavillon mit Theke und Edelstahl-Arbeitsbereich": {
    de: "Günstiger Verkaufs-Pavillon mit Theke und Edelstahl-Arbeitsbereich",
    en: "Affordable sales pavilion with counter and stainless steel work area",
    fr: "Pavillon de vente abordable avec comptoir et plan de travail inox",
    nl: "Voordelig verkooppaviljoen met toonbank en RVS werkruimte",
  },
  "Mietbarer Imbiss-Anhänger, 5 M, 1,5 T": {
    de: "Mietbarer Imbiss-Anhänger, 5 M, 1,5 T",
    en: "Food trailer to rent, 5 m, 1.5 t",
    fr: "Remorque snack à louer, 5 m, 1,5 t",
    nl: "Foodtrailer te huur, 5 m, 1,5 t",
  },
  "Mietbarer Verkaufs-Pavillon für Märkte, Events und saisonale Einsätze": {
    de: "Mietbarer Verkaufs-Pavillon für Märkte, Events und saisonale Einsätze",
    en: "Sales pavilion to rent for markets, events and seasonal use",
    fr: "Pavillon de vente à louer pour marchés, événements et saison",
    nl: "Verkooppaviljoen te huur voor markten, events en seizoen",
  },
  "was du kaufen möchtest.": { de: "was du kaufen möchtest.", en: "what you want to buy.", fr: "ce que vous voulez acheter.", nl: "wat je wilt kopen." },
  "was du mieten möchtest.": { de: "was du mieten möchtest.", en: "what you want to rent.", fr: "ce que vous voulez louer.", nl: "wat je wilt huren." },
  "Dein": { de: "Dein", en: "Your", fr: "Votre", nl: "Jouw" },
  "Was möchtest du": { de: "Was möchtest du", en: "What do you want to", fr: "Que souhaitez-vous", nl: "Wat wil je" },
  "konfigurieren?": { de: "konfigurieren?", en: "configure?", fr: "configurer ?", nl: "configureren?" },
  "Öffnungen und Ausstattung Schritt für Schritt festlegen — am Ende erhältst du dein individuelles Angebot.": {
    de: "Öffnungen und Ausstattung Schritt für Schritt festlegen — am Ende erhältst du dein individuelles Angebot.",
    en: "Set openings and equipment step by step; at the end you receive your individual quote.",
    fr: "Définissez les ouvertures et l'équipement étape par étape ; vous recevrez ensuite votre offre personnalisée.",
    nl: "Bepaal openingen en uitrusting stap voor stap; aan het einde ontvang je je persoonlijke offerte.",
  },
  "Modell, Fenster und Ausstattung Schritt für Schritt festlegen — am Ende erhältst du dein individuelles Angebot.": {
    de: "Modell, Fenster und Ausstattung Schritt für Schritt festlegen — am Ende erhältst du dein individuelles Angebot.",
    en: "Set model, windows and equipment step by step; at the end you receive your individual quote.",
    fr: "Définissez le modèle, les fenêtres et l'équipement étape par étape ; vous recevrez ensuite votre offre personnalisée.",
    nl: "Bepaal model, ramen en uitrusting stap voor stap; aan het einde ontvang je je persoonlijke offerte.",
  },
  "Wähle zuerst, ob du einen Imbiss-Anhänger oder einen Verkaufs-Pavillon konfigurieren möchtest.": {
    de: "Wähle zuerst, ob du einen Imbiss-Anhänger oder einen Verkaufs-Pavillon konfigurieren möchtest.",
    en: "First choose whether you want to configure a food trailer or a sales pavilion.",
    fr: "Choisissez d'abord si vous souhaitez configurer une remorque snack ou un pavillon de vente.",
    nl: "Kies eerst of je een foodtrailer of een verkooppaviljoen wilt configureren.",
  },
  "Wähle zwischen sofort verfügbaren Imbiss-Anhängern und Verkaufs-Pavillons. Über den Produktfilter kannst du beide Produktarten vergleichen.": {
    de: "Wähle zwischen sofort verfügbaren Imbiss-Anhängern und Verkaufs-Pavillons. Über den Produktfilter kannst du beide Produktarten vergleichen.",
    en: "Choose between available food trailers and sales pavilions. Use the product filter to compare both product types.",
    fr: "Choisissez entre remorques snack et pavillons de vente disponibles. Le filtre produit permet de comparer les deux types.",
    nl: "Kies tussen direct beschikbare foodtrailers en verkooppaviljoens. Met de productfilter kun je beide types vergelijken.",
  },
  "Wähle zwischen mietbaren Imbiss-Anhängern und Verkaufs-Pavillons. Über den Produktfilter kannst du beide Produktarten vergleichen.": {
    de: "Wähle zwischen mietbaren Imbiss-Anhängern und Verkaufs-Pavillons. Über den Produktfilter kannst du beide Produktarten vergleichen.",
    en: "Choose between rentable food trailers and sales pavilions. Use the product filter to compare both product types.",
    fr: "Choisissez entre remorques snack et pavillons de vente à louer. Le filtre produit permet de comparer les deux types.",
    nl: "Kies tussen foodtrailers en verkooppaviljoens te huur. Met de productfilter kun je beide types vergelijken.",
  },
  "Auf dem Weg zu dir": { de: "Auf dem Weg zu dir", en: "On the way to you", fr: "En route vers vous", nl: "Onderweg naar jou" },
  "Von Bremen": { de: "Von Bremen", en: "From Bremen", fr: "De Brême", nl: "Van Bremen" },
  "bis München.": { de: "bis München.", en: "to Munich.", fr: "à Munich.", nl: "tot München." },
  "Überall in Deutschland stehen MINO-Anhänger — und dahinter Menschen, die ihren Traum längst leben.": {
    de: "Überall in Deutschland stehen MINO-Anhänger — und dahinter Menschen, die ihren Traum längst leben.",
    en: "MINO trailers are all over Germany, behind them people already living their dream.",
    fr: "Des remorques MINO sont présentes partout en Allemagne, avec derrière elles des personnes qui vivent déjà leur rêve.",
    nl: "Overal in Duitsland staan MINO-trailers, met daarachter mensen die hun droom al leven.",
  },
  "Vorheriges Bild": { de: "Vorheriges Bild", en: "Previous image", fr: "Image précédente", nl: "Vorige afbeelding" },
  "Nächstes Bild": { de: "Nächstes Bild", en: "Next image", fr: "Image suivante", nl: "Volgende afbeelding" },
  "Bild anzeigen": { de: "Bild anzeigen", en: "Show image", fr: "Afficher l'image", nl: "Afbeelding tonen" },
  "Produktionsphase": { de: "Produktionsphase", en: "Production phase", fr: "Phase de production", nl: "Productiefase" },
  "Schließen": { de: "Schließen", en: "Close", fr: "Fermer", nl: "Sluiten" },
  "Impressum": { de: "Impressum", en: "Legal notice", fr: "Mentions légales", nl: "Impressum" },
  "Kontakt": { de: "Kontakt", en: "Contact", fr: "Contact", nl: "Contact" },
  "Über MINO": { de: "Über MINO", en: "About MINO", fr: "À propos de MINO", nl: "Over MINO" },
  "Aus der": { de: "Aus der", en: "Built from", fr: "Né de", nl: "Gebouwd vanuit" },
  "Praxis gebaut.": { de: "Praxis gebaut.", en: "real practice.", fr: "l'expérience.", nl: "de praktijk." },
  "Wir kommen selbst aus der Immobilien- und Gastronomiebranche. Genau deshalb wissen wir, wie wichtig verlässliches Equipment, faire Preise und eine Lösung sind, die im Alltag wirklich funktioniert.": {
    de: "Wir kommen selbst aus der Immobilien- und Gastronomiebranche. Genau deshalb wissen wir, wie wichtig verlässliches Equipment, faire Preise und eine Lösung sind, die im Alltag wirklich funktioniert.",
    en: "We come from the real estate and gastronomy industries ourselves. That is why we know how important reliable equipment, fair prices and a solution that truly works day to day are.",
    fr: "Nous venons nous-mêmes de l'immobilier et de la gastronomie. C'est pourquoi nous savons à quel point un équipement fiable, des prix justes et une solution réellement efficace au quotidien sont importants.",
    nl: "We komen zelf uit de vastgoed- en horecabranche. Juist daarom weten we hoe belangrijk betrouwbaar materiaal, eerlijke prijzen en een oplossing zijn die in de praktijk echt werkt.",
  },
  "Warum wir das machen": { de: "Warum wir das machen", en: "Why we do this", fr: "Pourquoi nous le faisons", nl: "Waarom we dit doen" },
  "Wir kennen": { de: "Wir kennen", en: "We know", fr: "Nous connaissons", nl: "Wij kennen" },
  "die Realität.": { de: "die Realität.", en: "the reality.", fr: "la réalité.", nl: "de praktijk." },
  "Wir beide sind selbst in der Immobilien- und Gastronomiebranche tätig und haben daran viel Spaß. Als wir unser eigenes Equipment aufstocken wollten, haben wir schnell gemerkt, wie viel man dabei lernen muss: Welche Ausstattung lohnt sich wirklich? Wo zahlt man zu viel? Und worauf kommt es an, wenn ein Konzept nicht nur gut aussehen, sondern jeden Tag Umsatz machen soll?": {
    de: "Wir beide sind selbst in der Immobilien- und Gastronomiebranche tätig und haben daran viel Spaß. Als wir unser eigenes Equipment aufstocken wollten, haben wir schnell gemerkt, wie viel man dabei lernen muss: Welche Ausstattung lohnt sich wirklich? Wo zahlt man zu viel? Und worauf kommt es an, wenn ein Konzept nicht nur gut aussehen, sondern jeden Tag Umsatz machen soll?",
    en: "We both work in real estate and gastronomy ourselves, and we enjoy it. When we wanted to expand our own equipment, we quickly realized how much there is to learn: which equipment is really worth it, where do you overpay, and what matters when a concept should not only look good but generate revenue every day?",
    fr: "Nous travaillons tous les deux dans l'immobilier et la gastronomie, avec beaucoup de plaisir. Lorsque nous avons voulu compléter notre propre équipement, nous avons vite compris tout ce qu'il fallait apprendre : quel équipement vaut vraiment la peine, où paie-t-on trop, et qu'est-ce qui compte quand un concept doit non seulement être beau mais générer du chiffre chaque jour ?",
    nl: "We werken allebei zelf in vastgoed en horeca, met veel plezier. Toen we onze eigen uitrusting wilden uitbreiden, merkten we snel hoeveel je daarbij moet leren: welke uitrusting loont echt, waar betaal je te veel en wat is belangrijk als een concept niet alleen mooi moet zijn, maar elke dag omzet moet draaien?",
  },
  "Genau aus dieser Erfahrung heraus haben wir unseren ersten Anhänger auf eigene Faust produziert. Dabei wurde klar: In mobiler Gastronomie steckt enormes Potenzial, aber Preis und Leistung müssen stimmen. Ein Anhänger oder Pavillon darf nicht unnötig kompliziert sein, sondern muss zu dem Geschäft passen, das dahintersteht.": {
    de: "Genau aus dieser Erfahrung heraus haben wir unseren ersten Anhänger auf eigene Faust produziert. Dabei wurde klar: In mobiler Gastronomie steckt enormes Potenzial, aber Preis und Leistung müssen stimmen. Ein Anhänger oder Pavillon darf nicht unnötig kompliziert sein, sondern muss zu dem Geschäft passen, das dahintersteht.",
    en: "That experience led us to produce our first trailer on our own. It became clear that mobile gastronomy has huge potential, but price and performance have to be right. A trailer or pavilion should not be unnecessarily complicated; it has to fit the business behind it.",
    fr: "C'est cette expérience qui nous a poussés à produire notre première remorque par nous-mêmes. Une chose est devenue claire : la gastronomie mobile a un potentiel énorme, mais le prix et la performance doivent être justes. Une remorque ou un pavillon ne doit pas être inutilement compliqué ; il doit correspondre à l'activité derrière.",
    nl: "Vanuit die ervaring hebben we onze eerste trailer zelf geproduceerd. Daarbij werd duidelijk: mobiele gastronomie heeft enorm potentieel, maar prijs en prestatie moeten kloppen. Een trailer of paviljoen moet niet onnodig ingewikkeld zijn, maar passen bij de onderneming erachter.",
  },
  "Heute möchten wir möglichst vielen Gastronomen helfen, ihr bestehendes Geschäft durch mobile Gastronomie zu erweitern, neue Standorte zu testen oder zusätzlichen Umsatz aufzubauen. Gleichzeitig wollen wir Startups und Jungunternehmer dabei unterstützen, ihr erstes eigenes Projekt greifbar und bezahlbar umzusetzen.": {
    de: "Heute möchten wir möglichst vielen Gastronomen helfen, ihr bestehendes Geschäft durch mobile Gastronomie zu erweitern, neue Standorte zu testen oder zusätzlichen Umsatz aufzubauen. Gleichzeitig wollen wir Startups und Jungunternehmer dabei unterstützen, ihr erstes eigenes Projekt greifbar und bezahlbar umzusetzen.",
    en: "Today we want to help as many gastronomy businesses as possible expand through mobile gastronomy, test new locations or create additional revenue. At the same time, we want to support startups and young entrepreneurs in making their first project tangible and affordable.",
    fr: "Aujourd'hui, nous voulons aider autant de restaurateurs que possible à développer leur activité grâce à la gastronomie mobile, tester de nouveaux emplacements ou créer du chiffre supplémentaire. Nous voulons aussi aider les startups et jeunes entrepreneurs à concrétiser leur premier projet de manière abordable.",
    nl: "Vandaag willen we zoveel mogelijk horecaondernemers helpen hun bestaande bedrijf uit te breiden met mobiele gastronomie, nieuwe locaties te testen of extra omzet op te bouwen. Tegelijk willen we startups en jonge ondernemers ondersteunen om hun eerste eigen project concreet en betaalbaar te realiseren.",
  },
  "Erfahrung": { de: "Erfahrung", en: "Experience", fr: "Expérience", nl: "Ervaring" },
  "Wir kennen die Anforderungen aus eigener Gastronomie-Praxis.": {
    de: "Wir kennen die Anforderungen aus eigener Gastronomie-Praxis.",
    en: "We know the requirements from our own gastronomy practice.",
    fr: "Nous connaissons les exigences grâce à notre propre expérience en gastronomie.",
    nl: "We kennen de eisen vanuit onze eigen horeca-ervaring.",
  },
  "Preis & Leistung": { de: "Preis & Leistung", en: "Price & performance", fr: "Prix & performance", nl: "Prijs & prestatie" },
  "Gute Ausstattung muss wirtschaftlich bleiben und zum Konzept passen.": {
    de: "Gute Ausstattung muss wirtschaftlich bleiben und zum Konzept passen.",
    en: "Good equipment has to remain economical and fit the concept.",
    fr: "Un bon équipement doit rester rentable et adapté au concept.",
    nl: "Goede uitrusting moet economisch blijven en bij het concept passen.",
  },
  "Umsetzung": { de: "Umsetzung", en: "Execution", fr: "Réalisation", nl: "Uitvoering" },
  "Vom ersten Paket bis zum individuellen Ausbau denken wir verkaufsnah.": {
    de: "Vom ersten Paket bis zum individuellen Ausbau denken wir verkaufsnah.",
    en: "From the first package to the custom build, we think close to real sales.",
    fr: "Du premier pack à l'aménagement individuel, nous pensons toujours proche de la vente.",
    nl: "Van het eerste pakket tot individuele afbouw denken we verkoopgericht.",
  },
  "Für Menschen,": { de: "Für Menschen,", en: "For people", fr: "Pour celles et ceux", nl: "Voor mensen" },
  "die starten wollen.": { de: "die starten wollen.", en: "who want to start.", fr: "qui veulent démarrer.", nl: "die willen starten." },
  "Manche wollen mit einem fertigen Anhänger direkt loslegen. Andere brauchen erst ein kleineres Setup, etwa einen Verkaufs-Pavillon, um ein Konzept zu testen. Für beides möchten wir eine klare, faire und verständliche Lösung anbieten.": {
    de: "Manche wollen mit einem fertigen Anhänger direkt loslegen. Andere brauchen erst ein kleineres Setup, etwa einen Verkaufs-Pavillon, um ein Konzept zu testen. Für beides möchten wir eine klare, faire und verständliche Lösung anbieten.",
    en: "Some want to start right away with a finished trailer. Others first need a smaller setup, such as a sales pavilion, to test a concept. We want to offer a clear, fair and understandable solution for both.",
    fr: "Certains veulent démarrer directement avec une remorque prête. D'autres ont d'abord besoin d'un format plus petit, par exemple un pavillon de vente, pour tester un concept. Nous voulons proposer une solution claire, juste et compréhensible pour les deux.",
    nl: "Sommigen willen direct starten met een afgewerkte trailer. Anderen hebben eerst een kleinere opstelling nodig, bijvoorbeeld een verkooppaviljoen, om een concept te testen. Voor beide willen we een duidelijke, eerlijke en begrijpelijke oplossing bieden.",
  },
  "Unser Ziel ist nicht, möglichst kompliziert zu planen. Unser Ziel ist, dass du eine Ausstattung bekommst, die zu deinem Produkt, deinem Budget und deinem nächsten Schritt passt.": {
    de: "Unser Ziel ist nicht, möglichst kompliziert zu planen. Unser Ziel ist, dass du eine Ausstattung bekommst, die zu deinem Produkt, deinem Budget und deinem nächsten Schritt passt.",
    en: "Our goal is not to make planning as complicated as possible. Our goal is that you get equipment that fits your product, your budget and your next step.",
    fr: "Notre objectif n'est pas de rendre la planification aussi compliquée que possible. Notre objectif est que vous obteniez un équipement adapté à votre produit, votre budget et votre prochaine étape.",
    nl: "Ons doel is niet om zo ingewikkeld mogelijk te plannen. Ons doel is dat je uitrusting krijgt die past bij je product, je budget en je volgende stap.",
  },
  "Die Gründung als UG (haftungsbeschränkt) befindet sich in Vorbereitung. Handelsregistereintrag und Umsatzsteuer-ID werden ergänzt, sobald sie vorliegen.": {
    de: "Die Gründung als UG (haftungsbeschränkt) befindet sich in Vorbereitung. Handelsregistereintrag und Umsatzsteuer-ID werden ergänzt, sobald sie vorliegen.",
    en: "The founding of the UG (haftungsbeschränkt) is currently underway. The commercial register entry and VAT ID will be added once available.",
    fr: "La création de l'UG (à responsabilité limitée) est en cours. L'inscription au registre du commerce et le numéro de TVA seront ajoutés dès qu'ils seront disponibles.",
    nl: "De oprichting als UG (beperkte aansprakelijkheid) is in voorbereiding. Handelsregisterinschrijving en btw-nummer worden aangevuld zodra deze beschikbaar zijn.",
  },
  "Angaben gemäß § 5 TMG": { de: "Angaben gemäß § 5 TMG", en: "Information according to § 5 TMG", fr: "Informations conformément au § 5 TMG", nl: "Informatie volgens § 5 TMG" },
  "Vertreten durch": { de: "Vertreten durch", en: "Represented by", fr: "Représenté par", nl: "Vertegenwoordigd door" },
  "Telefon": { de: "Telefon", en: "Phone", fr: "Téléphone", nl: "Telefoon" },
  "Registereintrag": { de: "Registereintrag", en: "Register entry", fr: "Inscription au registre", nl: "Registerinschrijving" },
  "Umsatzsteuer-ID": { de: "Umsatzsteuer-ID", en: "VAT ID", fr: "Numéro de TVA", nl: "Btw-nummer" },
  "Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV": {
    de: "Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV",
    en: "Responsible for content according to § 18 para. 2 MStV",
    fr: "Responsable du contenu selon le § 18 al. 2 MStV",
    nl: "Verantwoordelijk voor de inhoud volgens § 18 lid 2 MStV",
  },
  "Streitschlichtung": { de: "Streitschlichtung", en: "Dispute resolution", fr: "Règlement des litiges", nl: "Geschillenbeslechting" },
  "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:": {
    de: "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:",
    en: "The European Commission provides a platform for online dispute resolution (ODR):",
    fr: "La Commission européenne met à disposition une plateforme de règlement en ligne des litiges (RLL) :",
    nl: "De Europese Commissie biedt een platform voor online geschillenbeslechting (ODR):",
  },
  ". Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.": {
    de: ". Wir sind nicht verpflichtet und nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.",
    en: ". We are neither obliged nor willing to participate in dispute resolution proceedings before a consumer arbitration board.",
    fr: ". Nous ne sommes ni obligés ni disposés à participer à une procédure de règlement des litiges devant un organisme de médiation des consommateurs.",
    nl: ". Wij zijn niet verplicht en niet bereid deel te nemen aan geschillenbeslechtingsprocedures voor een consumentenarbitragecommissie.",
  },
  "Datenschutzerklärung": { de: "Datenschutzerklärung", en: "Privacy policy", fr: "Politique de confidentialité", nl: "Privacyverklaring" },
  "Diese Erklärung beschreibt den aktuellen technischen Stand der Website. Die Gründung als UG (haftungsbeschränkt) befindet sich in Vorbereitung. Bei neuen Diensten (z. B. Formularversand über einen Server, Analytics, Newsletter) muss dieser Text entsprechend erweitert werden.": {
    de: "Diese Erklärung beschreibt den aktuellen technischen Stand der Website. Die Gründung als UG (haftungsbeschränkt) befindet sich in Vorbereitung. Bei neuen Diensten (z. B. Formularversand über einen Server, Analytics, Newsletter) muss dieser Text entsprechend erweitert werden.",
    en: "This policy describes the current technical state of the website. The founding of the UG (haftungsbeschränkt) is currently underway. If new services are added, such as server-based form delivery, analytics or newsletters, this text must be expanded accordingly.",
    fr: "Cette déclaration décrit l'état technique actuel du site. La création de l'UG (à responsabilité limitée) est en cours. Si de nouveaux services sont ajoutés, par exemple envoi de formulaire via serveur, analytics ou newsletter, ce texte devra être complété.",
    nl: "Deze verklaring beschrijft de huidige technische staat van de website. De oprichting als UG (beperkte aansprakelijkheid) is in voorbereiding. Bij nieuwe diensten, zoals formulierverzending via een server, analytics of nieuwsbrief, moet deze tekst worden uitgebreid.",
  },
  "1. Verantwortliche Stelle": { de: "1. Verantwortliche Stelle", en: "1. Controller", fr: "1. Responsable du traitement", nl: "1. Verwerkingsverantwoordelijke" },
  "2. Hosting": { de: "2. Hosting", en: "2. Hosting", fr: "2. Hébergement", nl: "2. Hosting" },
  "Diese Website wird bei {provider} gehostet. Beim Aufruf der Seite verarbeitet der Hosting-Anbieter automatisch technische Zugriffsdaten (Server-Logfiles), z. B. IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seite und verwendeter Browser. Diese Verarbeitung erfolgt auf Grundlage unseres berechtigten Interesses an einem sicheren und funktionsfähigen Betrieb der Website (Art. 6 Abs. 1 lit. f DSGVO).": {
    de: "Diese Website wird bei {provider} gehostet. Beim Aufruf der Seite verarbeitet der Hosting-Anbieter automatisch technische Zugriffsdaten (Server-Logfiles), z. B. IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seite und verwendeter Browser. Diese Verarbeitung erfolgt auf Grundlage unseres berechtigten Interesses an einem sicheren und funktionsfähigen Betrieb der Website (Art. 6 Abs. 1 lit. f DSGVO).",
    en: "This website is hosted by {provider}. When the site is accessed, the hosting provider automatically processes technical access data (server log files), such as IP address, date and time of access, requested page and browser used. This processing is based on our legitimate interest in secure and functional website operation (Art. 6 para. 1 lit. f GDPR).",
    fr: "Ce site est hébergé par {provider}. Lors de l'accès au site, l'hébergeur traite automatiquement des données techniques d'accès (fichiers journaux serveur), par exemple l'adresse IP, la date et l'heure d'accès, la page consultée et le navigateur utilisé. Ce traitement repose sur notre intérêt légitime à assurer un fonctionnement sûr et fonctionnel du site (art. 6 al. 1 let. f RGPD).",
    nl: "Deze website wordt gehost bij {provider}. Bij het bezoeken van de site verwerkt de hostingprovider automatisch technische toegangsgegevens (serverlogbestanden), zoals IP-adres, datum en tijdstip van toegang, bezochte pagina en gebruikte browser. Deze verwerking is gebaseerd op ons gerechtvaardigd belang bij een veilige en goed functionerende website (art. 6 lid 1 sub f AVG).",
  },
  "3. Kontaktformular": { de: "3. Kontaktformular", en: "3. Contact form", fr: "3. Formulaire de contact", nl: "3. Contactformulier" },
  "Das Kontaktformular auf dieser Website übermittelt deine Eingaben nicht an einen Server von uns, sondern öffnet dein lokales E-Mail-Programm mit einer vorausgefüllten Nachricht. Der eigentliche Versand erfolgt direkt aus deinem E-Mail-Programm an {email}. Wir speichern die Formulareingaben zu keinem Zeitpunkt auf unseren Servern; die Verarbeitung der von dir gesendeten E-Mail erfolgt zur Bearbeitung deiner Anfrage (Art. 6 Abs. 1 lit. b bzw. f DSGVO).": {
    de: "Das Kontaktformular auf dieser Website übermittelt deine Eingaben nicht an einen Server von uns, sondern öffnet dein lokales E-Mail-Programm mit einer vorausgefüllten Nachricht. Der eigentliche Versand erfolgt direkt aus deinem E-Mail-Programm an {email}. Wir speichern die Formulareingaben zu keinem Zeitpunkt auf unseren Servern; die Verarbeitung der von dir gesendeten E-Mail erfolgt zur Bearbeitung deiner Anfrage (Art. 6 Abs. 1 lit. b bzw. f DSGVO).",
    en: "The contact form on this website does not transmit your entries to one of our servers; it opens your local email app with a pre-filled message. The actual message is sent directly from your email app to {email}. We do not store form entries on our servers at any time; the email you send is processed to handle your request (Art. 6 para. 1 lit. b or f GDPR).",
    fr: "Le formulaire de contact de ce site ne transmet pas vos saisies à l'un de nos serveurs ; il ouvre votre application e-mail locale avec un message prérempli. L'envoi réel se fait directement depuis votre application e-mail à {email}. Nous ne stockons à aucun moment les saisies du formulaire sur nos serveurs ; l'e-mail envoyé est traité pour répondre à votre demande (art. 6 al. 1 let. b ou f RGPD).",
    nl: "Het contactformulier op deze website verzendt je invoer niet naar een van onze servers, maar opent je lokale e-mailprogramma met een vooraf ingevuld bericht. De daadwerkelijke verzending gebeurt rechtstreeks vanuit je e-mailprogramma naar {email}. Wij slaan formulierinvoer nooit op onze servers op; de door jou verzonden e-mail wordt verwerkt om je aanvraag te behandelen (art. 6 lid 1 sub b of f AVG).",
  },
  "4. Cookies & Analyse-Tools": { de: "4. Cookies & Analyse-Tools", en: "4. Cookies & analytics tools", fr: "4. Cookies & outils d'analyse", nl: "4. Cookies & analysetools" },
  "Diese Website setzt keine Analyse- oder Tracking-Tools ein. Solange sich die Website im Aufbau befindet, verwenden wir ein technisch notwendiges Cookie (mino_access), das ausschließlich den vorab per Passwort erteilten Zugriff auf die Vorschau speichert. Es findet keine Auswertung statt, das Cookie wird nicht zu Marketing- oder Analysezwecken genutzt (Art. 6 Abs. 1 lit. f DSGVO).": {
    de: "Diese Website setzt keine Analyse- oder Tracking-Tools ein. Solange sich die Website im Aufbau befindet, verwenden wir ein technisch notwendiges Cookie (mino_access), das ausschließlich den vorab per Passwort erteilten Zugriff auf die Vorschau speichert. Es findet keine Auswertung statt, das Cookie wird nicht zu Marketing- oder Analysezwecken genutzt (Art. 6 Abs. 1 lit. f DSGVO).",
    en: "This website does not use analytics or tracking tools. While the website is under construction, we use a technically necessary cookie (mino_access) that solely stores the password-based access granted to the preview. No evaluation takes place, and the cookie is not used for marketing or analytics purposes (Art. 6 para. 1 lit. f GDPR).",
    fr: "Ce site n'utilise aucun outil d'analyse ou de suivi. Tant que le site est en construction, nous utilisons un cookie techniquement nécessaire (mino_access) qui stocke uniquement l'accès à l'aperçu accordé au préalable par mot de passe. Aucune évaluation n'a lieu, le cookie n'est pas utilisé à des fins de marketing ou d'analyse (art. 6 al. 1 let. f RGPD).",
    nl: "Deze website gebruikt geen analyse- of trackingtools. Zolang de website in opbouw is, gebruiken wij een technisch noodzakelijke cookie (mino_access) die uitsluitend de vooraf via wachtwoord verleende toegang tot de preview opslaat. Er vindt geen evaluatie plaats en de cookie wordt niet gebruikt voor marketing- of analysedoeleinden (art. 6 lid 1 sub f AVG).",
  },
  "5. Schriftarten": { de: "5. Schriftarten", en: "5. Fonts", fr: "5. Polices", nl: "5. Lettertypen" },
  "Wir verwenden Google-Schriftarten (Libre Franklin, Playfair Display), die lokal über unseren Server ausgeliefert werden. Es findet dazu keine Verbindung zu Servern von Google statt, es werden keine Daten an Google übertragen.": {
    de: "Wir verwenden Google-Schriftarten (Libre Franklin, Playfair Display), die lokal über unseren Server ausgeliefert werden. Es findet dazu keine Verbindung zu Servern von Google statt, es werden keine Daten an Google übertragen.",
    en: "We use Google fonts (Libre Franklin, Playfair Display) that are served locally from our server. No connection to Google servers is made for this, and no data is transmitted to Google.",
    fr: "Nous utilisons des polices Google (Libre Franklin, Playfair Display) servies localement depuis notre serveur. Aucune connexion aux serveurs Google n'est établie et aucune donnée n'est transmise à Google.",
    nl: "Wij gebruiken Google-lettertypen (Libre Franklin, Playfair Display) die lokaal via onze server worden geleverd. Hiervoor wordt geen verbinding met Google-servers gemaakt en er worden geen gegevens aan Google doorgegeven.",
  },
  "6. Deine Rechte": { de: "6. Deine Rechte", en: "6. Your rights", fr: "6. Vos droits", nl: "6. Je rechten" },
  "Du hast das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung deiner personenbezogenen Daten sowie auf Datenübertragbarkeit und Widerspruch gegen die Verarbeitung. Zudem hast du das Recht, dich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Wende dich dazu an {email}.": {
    de: "Du hast das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung deiner personenbezogenen Daten sowie auf Datenübertragbarkeit und Widerspruch gegen die Verarbeitung. Zudem hast du das Recht, dich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Wende dich dazu an {email}.",
    en: "You have the right to access, rectification, deletion and restriction of processing of your personal data, as well as data portability and objection to processing. You also have the right to lodge a complaint with a data protection supervisory authority. Contact {email} for this.",
    fr: "Vous disposez d'un droit d'accès, de rectification, d'effacement et de limitation du traitement de vos données personnelles, ainsi que d'un droit à la portabilité et d'opposition au traitement. Vous avez également le droit de déposer une plainte auprès d'une autorité de contrôle de la protection des données. Contactez {email} à ce sujet.",
    nl: "Je hebt recht op inzage, rectificatie, verwijdering en beperking van de verwerking van je persoonsgegevens, evenals op overdraagbaarheid van gegevens en bezwaar tegen verwerking. Daarnaast heb je het recht om een klacht in te dienen bij een toezichthoudende autoriteit voor gegevensbescherming. Neem hiervoor contact op via {email}.",
  },
};

export function translateCopy(text: string, language: LanguageCode) {
  return copyTranslations[text]?.[language] ?? text;
}

export function translateCopyList(items: string[], language: LanguageCode) {
  return items.map((item) => translateCopy(item, language));
}
